In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('C:/Users/HaripreethAvarur/Programs/Python/Pers/Machine Learning/CodeBasics ML/Data/homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
#preprocessing
df.bedrooms.median()

4.0

In [4]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [5]:
reg = linear_model.LinearRegression()
reg.fit(df[['area', 'bedrooms', 'age']],df.price)

LinearRegression()

In [6]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [7]:
reg.intercept_

221323.00186540408

In [8]:
reg.predict([[3000, 5, 30]])

array([577503.19082251])

In [9]:
reg.predict([[1000, 7, 10]])

array([464790.42526678])

In [10]:
reg.predict([[1000, 1, 1]])

array([353542.60597684])